spring.application.name=mendohard

# 1. Configuración de H2 en Modo Archivo (DATOS PERSISTENTES)
spring.datasource.url=jdbc:h2:file:./data/mendoharddb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=${MENDOHARD_DB_PASSWORD:mendohard2026}

# 2. Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Habilitar la consola de H2 en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 4. Configuración de Swagger/OpenAPI para documentar la API
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# 5. Configuración de Mail (Completar con tus credenciales de aplicación de Google)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mendohard26@gmail.com
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

