spring.application.name=mendohard

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mendoharddb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=${MENDOHARD_DB_PASSWORD:mendohard2026}

# JPA / Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# Spring profile
spring.profiles.active=dev

# Configuración de Swagger/OpenAPI
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Configuración de Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mendohard26@gmail.com
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
mendohard.security.jwt.secret=${JWT_SECRET_KEY:MendoHardSecretKey2026MendoHardSecretKey2026MendoHard}
mendohard.security.jwt.expiration-ms=86400000

# Maximo intentos de iniciar sesion
mendohard.business.max-login-attempts=10